### ISSUE TITLE
How can I read subtitles from a specific time of a mkv file?

### ISSUE THREAD

**Issue by charlnoc** [mathiasvr/matroska-subtitles#4] opened 2018-08-30 04:48 UTC
for example, if a mkv video file has length 1 hour, how can I read the embedded subtitles starting from 30 mins?

I have read the random access example, and have tried use different values for the [start] option, but they didn't work. So in other words, which type of value should I use for the [start] option?

**Comment by mathiasvr** [comment] 2018-08-31 21:50
The random access example is not very realistic, because we open a stream at a specific byte offset (using the start option). It was intended for working with active/live streams, such as video data being processed by a player, and reading subtitles on the fly.

In your case it might be easier to read the entire mkv file, as in the basic example, and observe when the subtitle timestamp, `subtitle.time`, is around your desired value.

So for 30m that would be `subtitle.time > 30 * 60 * 1000`, since `time` is in ms.

I'm closing this issue for now, but let me know if this doesn't solve the problem.

**Closed as completed by mathiasvr** 2018-08-31 21:50 UTC
